# Generated by Django 5.0.1 on 2024-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food and drink", "Food and Drink"),
                    ("bills", "Bills"),
                    ("social", "Social"),
                    ("sport", "Sport"),
                    ("misc", "Misc"),
                ],
                max_length=50,
            ),
        ),
    ]
